In [1]:
import tensorflow as tf

2023-02-18 13:06:57.978044: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-18 13:06:58.064393: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-18 13:06:58.450255: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.6/lib64
2023-02-18 13:06:58.450292: W tensorflow/compiler/xla/stream_executor/p

In [2]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

2023-02-18 13:07:42.197504: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-18 13:07:42.239018: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-18 13:07:42.258532: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-18 13:07:42.258663: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 16881408470240567523
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 4864081920
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 9082317265972371790
 physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 1660 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5"
 xla_global_id: 416903419]

In [3]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.11.0


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-02-18 13:10:12.622199: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-18 13:10:12.622408: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-18 13:10:12.622511: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-18 13:10:12.622831: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-18 13:10:12.622950: I tensorflow/compiler/xla/stream_executo

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 1.0228319 ,  0.655457  , -1.6071026 ,  0.02895033,  0.20846012,
         0.22383505, -0.35567847,  0.4958479 ,  0.3005517 ,  0.19592059]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.20864429, 0.14449659, 0.01503974, 0.07722701, 0.0924122 ,
        0.09384401, 0.05256868, 0.12318002, 0.10132677, 0.09126063]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.3661213

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2023-02-18 13:10:55.973862: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x1c5edb60 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-02-18 13:10:55.973886: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA GeForce GTX 1660 SUPER, Compute Capability 7.5
2023-02-18 13:10:55.977801: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-02-18 13:10:56.071647: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 [==============================] - 2s 893us/step - loss: 0.2933 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 2s 906us/step - loss: 0.1413 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 2s 884us/step - loss: 0.1058 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 2s 909us/step - loss: 0.0880 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 2s 910us/step - loss: 0.0745 - accuracy: 0.9768


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0791 - accuracy: 0.9749 - 269ms/epoch - 860us/step


[0.07909679412841797, 0.9749000072479248]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1597149e-09, 1.3232586e-10, 2.8347398e-07, 1.0362715e-05,
        1.2473875e-14, 3.5928227e-09, 2.0133022e-15, 9.9998915e-01,
        2.6486067e-08, 2.1610897e-07],
       [1.5342401e-07, 9.5789292e-05, 9.9981803e-01, 8.3558072e-05,
        8.5423243e-13, 1.2576137e-07, 2.6449393e-07, 9.5513094e-12,
        2.1039637e-06, 2.8463499e-14],
       [7.9069350e-06, 9.9889237e-01, 7.0780618e-05, 2.4992629e-05,
        5.1674040e-05, 4.5980229e-05, 6.2809420e-05, 3.8767396e-04,
        4.5391961e-04, 1.9910333e-06],
       [9.9997759e-01, 5.8956028e-11, 5.8753579e-07, 3.8530433e-07,
        3.9498289e-09, 9.3191657e-06, 8.8001325e-06, 1.3742023e-06,
        3.4652319e-07, 1.5132581e-06],
       [2.4682004e-06, 1.4990823e-08, 4.0892264e-06, 7.5226801e-08,
        9.9852800e-01, 2.6075642e-07, 3.5731418e-06, 9.6536183e-05,
        1.1681357e-06, 1.3637779e-03]], dtype=float32)>